# Generated by Django 3.2.3 on 2021-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rare_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='postReaction', to='rare_rest_api.Reaction'),
        ),
    ]
