# Generated by Django 3.2.3 on 2021-05-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rare_rest_api', '0002_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='rare_rest_api.rareuser'),
        ),
    ]
