# Generated by Django 3.2.3 on 2021-05-17 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rare_rest_api', '0003_alter_rareuser_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
