# Generated by Django 3.2.3 on 2021-05-17 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rare_rest_api', '0004_alter_rareuser_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
