# Generated by Django 3.2.3 on 2021-05-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rare_rest_api', '0005_alter_rareuser_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='username',
            field=models.CharField(default='goodManPaul', max_length=50),
            preserve_default=False,
        ),
    ]
